from .bolsones import Bolsones as BolsonesResource
from .bolsones import Bolson as BolsonResource
from .bolsonesventa import BolsonesVenta as BolsonesVentaResource
from .bolsonesventa import BolsonVenta as BolsonVentaResource
from .bolsonespendientes import BolsonesPendientes as BolsonesPendientesResource
from .bolsonespendientes import BolsonPendiente as BolsonPendienteResource
from .bolsonesprevios import BolsonesPrevios as BolsonesPreviosResource
from .bolsonesprevios import BolsonPrevio as BolsonPrevioResource
from .productos import Productos as ProductosResource
from .productos import Producto as ProductoResource
from .compras import Compras as ComprasResource
from .compras import Compra as CompraResource
from .clientes import Clientes as ClientesResource
from .clientes import Cliente as ClienteResource
from .proveedores import Proveedores as ProveedoresResource
from .proveedores import Proveedor as ProveedorResource
from .productosbolsones import ProductosBolsones as ProductosBolsonesResource
from .productosbolsones import ProductoBolson as ProductoBolsonResource