from .bolsones_ import Bolsones as bolsonesResource
from .bolsones_ import Bolson as bolsonesResource
from .bolsones_pendiente import Bolsones_pendientes as bolsones_pendientesResource
from .bolsones_pendiente import Bolson_pendiente as bolsones_pendientesResource
from .bolsones_previos import Bolsones_previos as bolsones_previosResource
from .bolsones_previos import Bolson_previo as bolsones_previosResource
from .bolsones_venta import Bolsones_venta as bolsones_ventaResource
from .bolsones_venta import Bolson_venta as bolsones_ventaResource
from .clientes import Clientes as clientesResource
from .clientes import Cliente as clientesResource
from .compras import  Compras as comprasResource
from .compras import Compra as comprasResource
from .productos import Productos as productosResource
from .productos import Producto as productosResource
from .proveedores import Proveedores as proveedoresResource
from .proveedores import Proveedor as proveedoresResource