from .bolsones_ import Bolsones as BolsonesResource
from .bolsones_ import Bolson as BolsonResource
from .bolsonespendiente import BolsonesPendientes as BolsonesPendientesResource
from .bolsonespendiente import BolsonPendiente as BolsonPendienteResource
from .bolsonesprevios import BolsonesPrevios as BolsonesPreviosResource
from .bolsonesprevios import BolsonPrevio as BolsonPrevioResource
from .bolsonesventa import BolsonesVenta as BolsonesVentaResource
from .bolsonesventa import BolsonVenta as BolsonVentaResource
from .clientes import Clientes as ClientesResource
from .clientes import Cliente as ClienteResource
from .compras import  Compras as ComprasResource
from .compras import Compra as CompraResource
from .productos import Productos as ProductosResource
from .productos import Producto as ProductoResource
from .proveedores import Proveedores as ProveedoresResource
from .proveedores import Proveedor as ProveedorResource